### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by ixkaito** [axies-ce-org/sugowaka35#1]
`main` ブランチにプッシュ・マージしたら、ビルドして `static` ブランチにプッシュ。

**Comment by akiya64** [comment]
参考
* [GitHub Actions でワークフロー中に発生した差分を Push する](https://zenn.dev/lollipop_onl/articles/eoz-gha-push-diffs)
* [pull request がマージされたときに pull_request ワークフローを実行する](https://docs.github.com/ja/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges)

**Comment by akiya64** [comment]
`main` ブランチへのプッシュで発火させず、PRがマージされたときのみ発火させたい場合は `pull_request` イベントを使う。  
プッシュ・マージどちらでも発火させたい場合は、`on:push:branches` パラメターでよい。

**Comment by akiya64** [comment]
## 権限の設定について
[リポジトリに対する GITHUB_TOKEN のアクセス許可の設定](https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-private-repository-forks)


> リポジトリへの書き込みアクセス権を持っている人は誰でも、ワークフロー ファイルの permissions キーを編集して、  
> GITHUB_TOKEN に付与されたアクセス許可を変更でき、必要に応じて追加または削除できます。  
> 詳細については、[permissions](https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#permissions) をご覧ください。

```
permissions: write-all
```
と設定することで、プッシュできる。


```
permissions:
  actions: write
```

上記権限のみだと、Actions からプッシュはできず、下記エラーとなる。

```
remote: Permission to axies-ce/sugowaka35.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/axies-ce/sugowaka35/': The requested URL returned error: 403
```

**Comment by akiya64** [comment]
`static` ブランチのフォルダ構成は

**Comment by akiya64** [comment]
誤ってクローズしてしまったため、再オープン

**Comment by ixkaito** [comment]
ありがとうございました！完了しましたのでクローズします。
