### ISSUE TITLE
リファクタリング

### ISSUE THREAD

**Issue by ixkaito** [axies-ce-org/sugowaka35#12]
https://github.com/axies-ce-org/sugowaka35/blob/cb18e0af144cd040ac30d1e4f78ef8b412f22953/src/pages/index.astro#L98

@ArisaSadano ここはわざわざこうしなくても、データ側で以下のように書けばいけると思います。

```
title: <>1行目<br />2行目</>,
```

**Comment by arisaaaada** [comment]
@ixkaito 
それでは無理だったので`split`を使っていたのですが
<img width="756" alt="image" src="https://user-images.githubusercontent.com/61670425/229653993-79e97622-a788-4716-aebc-0f6385c2e12e.png">

他の記述が間違っているのでしょうか？

**Comment by ixkaito** [comment]
対応済みなのでクローズします。
