### ISSUE TITLE
Add alt text

### ISSUE THREAD

**Issue by ixkaito** [axies-ce-org/sugowaka35#26]
@arisaaaada 必要な代替テキストの入力をお願いします。

例：
![image](https://github.com/axies-ce-org/sugowaka35/assets/5457539/59759ea8-ca5f-456c-91a5-e68386de01d6)

**Comment by arisaaaada** [comment]
@ixkaito 
ご指摘いただいた画像を含め、本文中で言及されていない挿絵には `alt` を入れていませんでしたが、全てに挿入しますか？
<img width="517" alt="image" src="https://github.com/axies-ce-org/sugowaka35/assets/61670425/0b8f44e5-7288-4e8c-a64f-f0d09769a2c9">
<img width="469" alt="image" src="https://github.com/axies-ce-org/sugowaka35/assets/61670425/1d2309cb-61d3-42fb-805f-a3566bbb61d9">

**Comment by ixkaito** [comment]
@arisaaaada むしろ「本文中で言及されていない」コンテンツのほうが代替テキストが必要になると思いますが、文脈にも寄ります。あやかさんにも確認取りながら進めてもらえますか？

**Comment by arisaaaada** [comment]
@ixkaito かしこまりました。

**Comment by ixkaito** [comment]
@arisaaaada ありがとうございます。今もう一度確認しましたが、イラストになってるのはほぼ挿絵という位置づけですかね。それなら `alt=""` でもいいかもしれません。念のため明日でいいのであやかさんに確認してみて、そういう意図で文脈に影響がなければ対応しなくても大丈夫です。

**Comment by arisaaaada** [comment]
@ixkaito 
言葉足らずでした、すみません。`alt=""` の図は全て挿絵と判断したものです。それ以外は中身を記述し、英訳もいただいていますが、 `alt` を入れるかどうかは勝手に判断したので、改めて明日あやかさんに確認させていただきます。
